Removing coverage dependence
After v7.4.3, coverage causes netCDF4 to report a runtime error

RuntimeError: NetCDF: Not a valid ID

It is not clear to me why this happens, but it is reliable. v7.4.4
and above cause the error, which can be bypassed by downgrading
coverage or by using pytest directly. The test does not strictly
depend on increasing coverage, so I am removing it.